//! Byte-parity gate: caladon-core MUST produce output byte-identical to the Python `swifty_crypto`
//! reference. Vectors are generated by `tests/generate_vectors.py` (the oracle). This is the P1
//! gate (R1: Argon2id/HKDF divergence) — see internal build notes.
//!
//! Regenerate fixtures first:
//!   PYTHONPATH=. uv run --with pynacl --with cryptography python caladon-core/tests/generate_vectors.py

use base64::Engine;
use caladon_core::{envelope, kdf, padding, passkey, ratchet, seed_auth, seed_codec, session};
use serde::Deserialize;
use std::fs;

fn b64d(s: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD.decode(s).expect("valid base64")
}

#[derive(Deserialize)]
struct Vectors {
    argon2id: Vec<Argon2Vec>,
    hkdf: Vec<HkdfVec>,
    account_id: Vec<AccountVec>,
    ed25519_pub: Vec<EdVec>,
    padding: Vec<PadVec>,
    envelope: Vec<EnvVec>,
    session: Vec<SessionVec>,
    low_order: Vec<LowOrderVec>,
    ratchet_message_key: Vec<MsgKeyVec>,
    ratchet_advance: Vec<AdvanceVec>,
    ratchet_device_root: Vec<DeviceRootVec>,
    ratchet_kid: Vec<KidVec>,
    seed_auth: Vec<SeedAuthVec>,
    seed_codec: Vec<SeedCodecVec>,
}
#[derive(Deserialize)]
struct Argon2Vec { seed: String, salt: String, opslimit: u32, memlimit: u32, root: String }
#[derive(Deserialize)]
struct HkdfVec { root: String, label: String, length: usize, out: String }
#[derive(Deserialize)]
struct AccountVec { root: String, account_id: String }
#[derive(Deserialize)]
struct EdVec { root: String, pub_: Option<String>, #[serde(rename = "pub")] pubkey: Option<String> }
#[derive(Deserialize)]
struct PadVec { plaintext: String, padded_len: usize, padded: String }
#[derive(Deserialize)]
struct EnvVec { key: String, account_id: String, purpose: String, v: i64, nonce: String, aad: String, plaintext: String, ct: String }
#[derive(Deserialize)]
struct SessionVec {
    client_priv: String, cvm_priv: String, client_pub: String, cvm_pub: String,
    session_key: String, account_id: String,
    wmk: String, wmk_nonce: String, wmk_v: i64, wmk_ct: String,
    chat_plaintext: String, chat_nonce: String, chat_v: i64, chat_ct: String,
}
#[derive(Deserialize)]
struct LowOrderVec { #[allow(dead_code)] label: String, client_priv: String, peer_pub: String, rejected: bool }
#[derive(Deserialize)]
struct MsgKeyVec { transcript_root: String, step: i64, message_key: String }
#[derive(Deserialize)]
struct AdvanceVec { step: i64, message_key: String }
#[derive(Deserialize)]
struct DeviceRootVec { transcript_root: String, device_id: String, device_root: String }
#[derive(Deserialize)]
struct KidVec { step: i64, device_id: Option<String>, kid: String }
#[derive(Deserialize)]
struct SeedAuthVec {
    ed25519_seed: String, ed25519_pub: String, account_id: String, ts: i64,
    method: String, path: String, canonical: String, sig: String, header: String,
}
#[derive(Deserialize)]
struct SeedCodecVec { seed: String, encoded: String }

fn load() -> Vectors {
    let p = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors.json");
    let raw = fs::read_to_string(p)
        .unwrap_or_else(|_| panic!("missing {p} — run generate_vectors.py first"));
    serde_json::from_str(&raw).expect("vectors.json parses")
}

#[test]
fn argon2id_parity() {
    for v in load().argon2id {
        let got = kdf::argon2id(&b64d(&v.seed), &b64d(&v.salt), v.opslimit, v.memlimit)
            .expect("argon2id ok");
        assert_eq!(got.to_vec(), b64d(&v.root), "argon2id mismatch (opslimit={}, memlimit={})", v.opslimit, v.memlimit);
    }
}

#[test]
fn hkdf_parity() {
    for v in load().hkdf {
        let got = kdf::hkdf(&b64d(&v.root), &v.label, v.length);
        assert_eq!(got, b64d(&v.out), "hkdf mismatch (label={})", v.label);
    }
}

#[test]
fn account_id_parity() {
    for v in load().account_id {
        assert_eq!(kdf::derive_account_id(&b64d(&v.root)), v.account_id, "account_id mismatch");
    }
}

#[test]
fn ed25519_pub_parity() {
    for v in load().ed25519_pub {
        let expected = v.pubkey.or(v.pub_).expect("pub field");
        assert_eq!(kdf::derive_ed25519_public(&b64d(&v.root)).to_vec(), b64d(&expected), "ed25519 pub mismatch");
    }
}

#[test]
fn padding_parity() {
    for v in load().padding {
        let pt = b64d(&v.plaintext);
        let padded = padding::pad(&pt).expect("pad ok");
        assert_eq!(padded.len(), v.padded_len, "pad length mismatch for {} bytes", pt.len());
        assert_eq!(padded, b64d(&v.padded), "pad bytes mismatch for {} bytes", pt.len());
        assert_eq!(padding::unpad(&padded).expect("unpad ok"), pt, "unpad round-trip mismatch");
    }
}

#[test]
fn envelope_parity() {
    for v in load().envelope {
        let key = b64d(&v.key);
        let nonce = b64d(&v.nonce);
        let pt = b64d(&v.plaintext);
        // AAD parity: SHA-256("{account_id}\n{purpose}\n{v}").
        assert_eq!(envelope::aad(&v.account_id, &v.purpose, v.v).to_vec(), b64d(&v.aad), "aad mismatch");
        // ct parity: deterministic seal with the fixed nonce == the Python/libsodium ct.
        let ct = envelope::seal_with_nonce(&key, &pt, &v.account_id, &v.purpose, v.v, &nonce)
            .expect("seal ok");
        assert_eq!(ct, b64d(&v.ct), "envelope ct mismatch (purpose={})", v.purpose);
        // open round-trips to the plaintext (AAD re-derived & checked).
        let opened = envelope::open_bound(&key, &nonce, &ct, &v.account_id, &v.purpose, v.v)
            .expect("open ok");
        assert_eq!(opened, pt, "envelope open mismatch");
    }
}

#[test]
fn envelope_tamper_fails_closed() {
    let v = &load().envelope[1]; // non-empty plaintext
    let key = b64d(&v.key);
    let nonce = b64d(&v.nonce);
    let aad = b64d(&v.aad);
    let mut ct = b64d(&v.ct);
    // Tamper the ciphertext: open must fail.
    ct[0] ^= 0x01;
    assert_eq!(envelope::open(&key, &nonce, &aad, &ct), Err(envelope::EnvelopeError::OpenFailed));
    // Untampered opens fine.
    let good = b64d(&v.ct);
    assert!(envelope::open(&key, &nonce, &aad, &good).is_ok());
    // Tamper the AAD (wrong purpose/account): open must fail (the tag covers the AAD).
    let bad_aad = envelope::aad("acct-OTHER-XXXXXXXX", &v.purpose, v.v);
    assert_eq!(envelope::open(&key, &nonce, &bad_aad, &good), Err(envelope::EnvelopeError::OpenFailed));
    // open_bound with the wrong account_id derives a different AAD and fails.
    assert_eq!(
        envelope::open_bound(&key, &nonce, &good, "acct-WRONGWRONGWR", &v.purpose, v.v),
        Err(envelope::EnvelopeError::OpenFailed)
    );
}

#[test]
fn session_parity() {
    for v in load().session {
        let client_priv = b64d(&v.client_priv);
        let cvm_priv = b64d(&v.cvm_priv);
        let client_pub = b64d(&v.client_pub);
        let cvm_pub = b64d(&v.cvm_pub);
        // public-key derivation parity.
        assert_eq!(session::x25519_public(&client_priv).unwrap().to_vec(), client_pub, "client pub mismatch");
        assert_eq!(session::x25519_public(&cvm_priv).unwrap().to_vec(), cvm_pub, "cvm pub mismatch");
        // SK parity (client side) + both sides agree.
        let sk_client = session::derive_session_key(&client_priv, &cvm_pub, &client_pub, &cvm_pub).unwrap();
        let sk_cvm = session::derive_session_key(&cvm_priv, &client_pub, &client_pub, &cvm_pub).unwrap();
        assert_eq!(sk_client.to_vec(), b64d(&v.session_key), "session key mismatch");
        assert_eq!(sk_client, sk_cvm, "client/cvm session keys disagree");
        // WMK seal parity + CVM open round-trip.
        let wmk = b64d(&v.wmk);
        let wmk_nonce = b64d(&v.wmk_nonce);
        let wmk_ct = session::seal_wmk_with_nonce(&sk_client, &wmk, &v.account_id, v.wmk_v, &wmk_nonce).unwrap();
        assert_eq!(wmk_ct, b64d(&v.wmk_ct), "wmk ct mismatch");
        let opened_wmk = session::open_wmk(&sk_cvm, &wmk_nonce, &wmk_ct, &v.account_id, v.wmk_v).unwrap();
        assert_eq!(opened_wmk, wmk, "open_wmk round-trip mismatch");
        // chat seal parity + open round-trip.
        let chat_pt = b64d(&v.chat_plaintext);
        let chat_nonce = b64d(&v.chat_nonce);
        let chat_ct = session::seal_chat_with_nonce(&sk_client, &chat_pt, &v.account_id, v.chat_v, &chat_nonce).unwrap();
        assert_eq!(chat_ct, b64d(&v.chat_ct), "chat ct mismatch");
        assert_eq!(
            session::open_chat(&sk_cvm, &chat_nonce, &chat_ct, &v.account_id, v.chat_v).unwrap(),
            chat_pt, "open_chat round-trip mismatch"
        );
    }
}

#[test]
fn session_low_order_rejected() {
    for v in load().low_order {
        let client_priv = b64d(&v.client_priv);
        let peer = b64d(&v.peer_pub);
        let res = session::derive_session_key(&client_priv, &peer, &client_priv, &peer);
        // Python `cryptography` rejected every one of these; Rust MUST reject too (fail-closed).
        assert!(v.rejected, "fixture expects rejection");
        assert_eq!(res, Err(session::SessionError::LowOrderPoint),
                   "low-order peer key must be rejected (label fixture)");
    }
}

#[test]
fn ratchet_message_key_parity() {
    for v in load().ratchet_message_key {
        let root = b64d(&v.transcript_root);
        assert_eq!(
            ratchet::message_key_at(&root, v.step).unwrap(),
            b64d(&v.message_key), "message_key_at({}) mismatch", v.step
        );
    }
}

#[test]
fn ratchet_advance_parity() {
    let vs = load();
    // Re-derive the same root the generator used (transcript_root of roots[0]).
    let root = b64d(&vs.ratchet_message_key[0].transcript_root);
    let mut r = ratchet::TranscriptRatchet::new(&root);
    for v in vs.ratchet_advance {
        let (step, mk) = r.advance();
        assert_eq!(step, v.step, "advance step mismatch");
        assert_eq!(mk, b64d(&v.message_key), "advance message_key mismatch at step {}", v.step);
    }
}

#[test]
fn ratchet_device_root_parity() {
    for v in load().ratchet_device_root {
        let root = b64d(&v.transcript_root);
        assert_eq!(
            ratchet::device_transcript_root(&root, &v.device_id).unwrap(),
            b64d(&v.device_root), "device_transcript_root({}) mismatch", v.device_id
        );
    }
}

#[test]
fn ratchet_kid_parity() {
    for v in load().ratchet_kid {
        let kid = ratchet::transcript_kid(v.step, v.device_id.as_deref()).unwrap();
        assert_eq!(kid, v.kid, "transcript_kid mismatch");
        // round-trip parse.
        let (dev, step) = ratchet::parse_transcript_kid(&kid).unwrap();
        assert_eq!(dev, v.device_id, "parsed device_id mismatch");
        assert_eq!(step, v.step, "parsed step mismatch");
        assert_eq!(ratchet::step_from_kid(&kid).unwrap(), v.step, "step_from_kid mismatch");
    }
}

#[test]
fn seed_auth_parity() {
    for v in load().seed_auth {
        let seed: [u8; 32] = b64d(&v.ed25519_seed).try_into().expect("32-byte ed seed");
        let pubkey: [u8; 32] = b64d(&v.ed25519_pub).try_into().expect("32-byte ed pub");
        // canonical-bytes parity.
        assert_eq!(
            seed_auth::canonical(&v.account_id, v.ts, &v.method, &v.path),
            b64d(&v.canonical), "canonical mismatch"
        );
        // signature parity (Ed25519 deterministic).
        assert_eq!(
            seed_auth::sign(&seed, &v.account_id, v.ts, &v.method, &v.path).to_vec(),
            b64d(&v.sig), "signature mismatch"
        );
        // Authorization header parity (byte-identical to gateway/Swift).
        assert_eq!(
            seed_auth::authorization_header(&seed, &v.account_id, v.ts, &v.method, &v.path).unwrap(),
            v.header, "authorization header mismatch"
        );
        // gateway-side verify: parse the header, then verify the signature against the pubkey.
        let req = seed_auth::parse_auth_header(&v.header).expect("parse header");
        assert_eq!(req.account_id, v.account_id);
        assert_eq!(req.ts, v.ts);
        seed_auth::verify(&pubkey, &req, &v.method, &v.path, v.ts).expect("verify ok");
        // tamper: wrong path must fail.
        assert_eq!(
            seed_auth::verify(&pubkey, &req, &v.method, "/v1/WRONG", v.ts),
            Err(seed_auth::SeedAuthError::InvalidSignature)
        );
        // tamper: stale timestamp must fail.
        assert_eq!(
            seed_auth::verify(&pubkey, &req, &v.method, &v.path, v.ts + seed_auth::FRESHNESS_WINDOW_S + 1),
            Err(seed_auth::SeedAuthError::StaleTimestamp)
        );
    }
}

#[test]
fn seed_codec_parity() {
    for v in load().seed_codec {
        let seed = b64d(&v.seed);
        let encoded = seed_codec::encode(&seed).expect("encode ok");
        assert_eq!(encoded, v.encoded, "seed_codec encode mismatch");
        // round-trip decode.
        assert_eq!(seed_codec::decode(&encoded).expect("decode ok"), seed, "decode round-trip mismatch");
        // case-insensitive + Crockford normalisation (I/L->1, O->0) + whitespace tolerated.
        let lowered = encoded.to_lowercase();
        assert_eq!(seed_codec::decode(&lowered).expect("lower decode"), seed, "lowercase decode mismatch");
    }
}

#[test]
fn seed_codec_checksum_and_strict() {
    let seed: Vec<u8> = (0u8..32).collect();
    let mut encoded = seed_codec::encode(&seed).unwrap();
    // Flip a payload character -> checksum mismatch.
    let bytes: Vec<char> = encoded.chars().collect();
    // Find a flippable alnum char (not '-') near the start and change it.
    let pos = bytes.iter().position(|c| *c != '-').unwrap();
    let replacement = if bytes[pos] == '1' { '2' } else { '1' };
    encoded.replace_range(
        encoded.char_indices().nth(pos).map(|(i, c)| i..i + c.len_utf8()).unwrap(),
        &replacement.to_string(),
    );
    assert!(matches!(seed_codec::decode(&encoded), Err(seed_codec::SeedError::BadChecksum) | Err(seed_codec::SeedError::BadLength)),
            "corrupted seed must be rejected");
    // Bad character (U is excluded from Crockford) -> BadCharacter.
    assert_eq!(seed_codec::decode("UUUU"), Err(seed_codec::SeedError::BadCharacter));
}

#[test]
fn passkey_round_trip_and_tamper() {
    // No Python oracle — round-trip + a fixed vector for the deterministic wrapping KEY.
    let prf: Vec<u8> = (0u8..32).collect();
    let seed: Vec<u8> = (0u8..32).map(|i| i.wrapping_mul(3)).collect();
    // Deterministic wrapping key (HKDF) — stable fixture regardless of AEAD nonce.
    let key = passkey::passkey_derive_wrapping_key(&prf).unwrap();
    // Fixed vector: assert the key matches the independently-computed HKDF (kdf::hkdf has its own
    // parity gate), proving passkey uses the same HKDF construction.
    let expected_key = {
        use hkdf::Hkdf;
        use sha2::Sha256;
        let hk = Hkdf::<Sha256>::new(None, &prf);
        let mut k = [0u8; 32];
        hk.expand(passkey::WRAPPING_LABEL, &mut k).unwrap();
        k
    };
    assert_eq!(key, expected_key, "wrapping key != HKDF(prf, label)");

    // Round-trip (random nonce).
    let (nonce, ct) = passkey::wrap_seed(&prf, &seed).unwrap();
    assert_eq!(passkey::unwrap_seed(&prf, &nonce, &ct).unwrap(), seed, "unwrap round-trip mismatch");

    // Deterministic-nonce wrap reproduces a fixed ct (self-consistency vector).
    let fixed_nonce = [0x5au8; passkey::NONCE_LEN];
    let ct_a = passkey::wrap_seed_with_nonce(&prf, &seed, &fixed_nonce).unwrap();
    let ct_b = passkey::wrap_seed_with_nonce(&prf, &seed, &fixed_nonce).unwrap();
    assert_eq!(ct_a, ct_b, "deterministic wrap not reproducible");
    assert_eq!(passkey::unwrap_seed(&prf, &fixed_nonce, &ct_a).unwrap(), seed);

    // Tamper: wrong PRF -> unwrap fails closed.
    let wrong_prf: Vec<u8> = (0u8..32).map(|i| i ^ 0xff).collect();
    assert_eq!(passkey::unwrap_seed(&wrong_prf, &nonce, &ct), Err(passkey::PasskeyError::UnwrapFailed));
    // Tamper: flipped ciphertext byte -> fails closed.
    let mut bad = ct.clone();
    bad[0] ^= 0x01;
    assert_eq!(passkey::unwrap_seed(&prf, &nonce, &bad), Err(passkey::PasskeyError::UnwrapFailed));
}
