/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const account_id: (a: number, b: number) => [number, number];
export const argon2id: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const authorization_header: (a: number, b: number, c: number, d: number, e: bigint, f: number, g: number, h: number, i: number) => [number, number, number, number];
export const challenge_hex: (a: number, b: number) => [number, number];
export const derive_session_key: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const ed25519_public: (a: number, b: number) => [number, number];
export const open_chat: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint) => [number, number, number, number];
export const open_wmk: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint) => [number, number, number, number];
export const pad: (a: number, b: number) => [number, number, number, number];
export const passkey_derive_wrapping_key: (a: number, b: number) => [number, number, number, number];
export const passkey_unwrap_seed: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const passkey_wrap_seed: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const seal_chat: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint) => [number, number, number, number];
export const seal_wmk: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint) => [number, number, number, number];
export const seed_decode: (a: number, b: number) => [number, number, number, number];
export const seed_encode: (a: number, b: number) => [number, number, number, number];
export const unpad: (a: number, b: number) => [number, number, number, number];
export const verify_quote_sync: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number, number];
export const wmk: (a: number, b: number) => [number, number];
export const x25519_public: (a: number, b: number) => [number, number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
