// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(caladon_coreFFI)
import caladon_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_caladon_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_caladon_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * The client-shipped pinned set (no TOFU). `measurements` = hex(mr_td‖rtmr0‖rtmr1‖rtmr2).
 */
public struct PinnedSet {
    public var measurements: [String]
    public var composeHashes: [String]
    public var workloadIds: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(measurements: [String], composeHashes: [String], workloadIds: [String]) {
        self.measurements = measurements
        self.composeHashes = composeHashes
        self.workloadIds = workloadIds
    }
}



extension PinnedSet: Equatable, Hashable {
    public static func ==(lhs: PinnedSet, rhs: PinnedSet) -> Bool {
        if lhs.measurements != rhs.measurements {
            return false
        }
        if lhs.composeHashes != rhs.composeHashes {
            return false
        }
        if lhs.workloadIds != rhs.workloadIds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(measurements)
        hasher.combine(composeHashes)
        hasher.combine(workloadIds)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePinnedSet: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PinnedSet {
        return
            try PinnedSet(
                measurements: FfiConverterSequenceString.read(from: &buf), 
                composeHashes: FfiConverterSequenceString.read(from: &buf), 
                workloadIds: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PinnedSet, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.measurements, into: &buf)
        FfiConverterSequenceString.write(value.composeHashes, into: &buf)
        FfiConverterSequenceString.write(value.workloadIds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinnedSet_lift(_ buf: RustBuffer) throws -> PinnedSet {
    return try FfiConverterTypePinnedSet.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinnedSet_lower(_ value: PinnedSet) -> RustBuffer {
    return FfiConverterTypePinnedSet.lower(value)
}


/**
 * The fail-closed verdict (mirrors the Swift `Verdict` + the `measurement_matched` diagnostic).
 */
public struct Verdict {
    public var ok: Bool
    public var reason: VerdictReason
    public var measurementMatched: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ok: Bool, reason: VerdictReason, measurementMatched: Bool) {
        self.ok = ok
        self.reason = reason
        self.measurementMatched = measurementMatched
    }
}



extension Verdict: Equatable, Hashable {
    public static func ==(lhs: Verdict, rhs: Verdict) -> Bool {
        if lhs.ok != rhs.ok {
            return false
        }
        if lhs.reason != rhs.reason {
            return false
        }
        if lhs.measurementMatched != rhs.measurementMatched {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ok)
        hasher.combine(reason)
        hasher.combine(measurementMatched)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerdict: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Verdict {
        return
            try Verdict(
                ok: FfiConverterBool.read(from: &buf), 
                reason: FfiConverterTypeVerdictReason.read(from: &buf), 
                measurementMatched: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Verdict, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.ok, into: &buf)
        FfiConverterTypeVerdictReason.write(value.reason, into: &buf)
        FfiConverterBool.write(value.measurementMatched, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerdict_lift(_ buf: RustBuffer) throws -> Verdict {
    return try FfiConverterTypeVerdict.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerdict_lower(_ value: Verdict) -> RustBuffer {
    return FfiConverterTypeVerdict.lower(value)
}


/**
 * Metadata-padding error (mirrors the UDL `PadError`).
 */
public enum PadError {

    
    
    case TooLong
    case TooShort
    case DeclaredLenExceedsBuffer
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePadError: FfiConverterRustBuffer {
    typealias SwiftType = PadError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PadError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .TooLong
        case 2: return .TooShort
        case 3: return .DeclaredLenExceedsBuffer

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PadError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .TooLong:
            writeInt(&buf, Int32(1))
        
        
        case .TooShort:
            writeInt(&buf, Int32(2))
        
        
        case .DeclaredLenExceedsBuffer:
            writeInt(&buf, Int32(3))
        
        }
    }
}


extension PadError: Equatable, Hashable {}

extension PadError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


/**
 * Passkey-PRF seed-custody error (mirrors the UDL `PasskeyError`).
 */
public enum PasskeyError {

    
    
    case BadPrfLength
    case BadSeedLength
    /**
     * Unwrap failed — wrong passkey/PRF, or a tampered blob. Fail closed.
     */
    case UnwrapFailed
    case Envelope
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePasskeyError: FfiConverterRustBuffer {
    typealias SwiftType = PasskeyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PasskeyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .BadPrfLength
        case 2: return .BadSeedLength
        case 3: return .UnwrapFailed
        case 4: return .Envelope

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PasskeyError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .BadPrfLength:
            writeInt(&buf, Int32(1))
        
        
        case .BadSeedLength:
            writeInt(&buf, Int32(2))
        
        
        case .UnwrapFailed:
            writeInt(&buf, Int32(3))
        
        
        case .Envelope:
            writeInt(&buf, Int32(4))
        
        }
    }
}


extension PasskeyError: Equatable, Hashable {}

extension PasskeyError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


/**
 * Sealed-channel error (mirrors the UDL `SealError`).
 */
public enum SealError {

    
    
    case BadKey
    case BadNonce
    case LowOrderPoint
    case OpenFailed
    case SealFailed
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSealError: FfiConverterRustBuffer {
    typealias SwiftType = SealError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SealError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .BadKey
        case 2: return .BadNonce
        case 3: return .LowOrderPoint
        case 4: return .OpenFailed
        case 5: return .SealFailed

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SealError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .BadKey:
            writeInt(&buf, Int32(1))
        
        
        case .BadNonce:
            writeInt(&buf, Int32(2))
        
        
        case .LowOrderPoint:
            writeInt(&buf, Int32(3))
        
        
        case .OpenFailed:
            writeInt(&buf, Int32(4))
        
        
        case .SealFailed:
            writeInt(&buf, Int32(5))
        
        }
    }
}


extension SealError: Equatable, Hashable {}

extension SealError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


/**
 * Seed-codec error (mirrors the UDL `SeedError`).
 */
public enum SeedError {

    
    
    case BadLength
    case BadChecksum
    case BadCharacter
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSeedError: FfiConverterRustBuffer {
    typealias SwiftType = SeedError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SeedError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .BadLength
        case 2: return .BadChecksum
        case 3: return .BadCharacter

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SeedError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .BadLength:
            writeInt(&buf, Int32(1))
        
        
        case .BadChecksum:
            writeInt(&buf, Int32(2))
        
        
        case .BadCharacter:
            writeInt(&buf, Int32(3))
        
        }
    }
}


extension SeedError: Equatable, Hashable {}

extension SeedError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The A7 failure→code table (attestation-evidence.md §1). Mirrors the Swift `VerdictReason`.
 */

public enum VerdictReason {
    
    case ok
    case quoteSigInvalid
    case tcbOutOfDate
    case collateralStale
    case measurementUnpinned
    case composeMismatch
    case appIdMismatch
    case bindingMismatch
    case noLogAbsent
    case regimeUnsupported
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerdictReason: FfiConverterRustBuffer {
    typealias SwiftType = VerdictReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VerdictReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ok
        
        case 2: return .quoteSigInvalid
        
        case 3: return .tcbOutOfDate
        
        case 4: return .collateralStale
        
        case 5: return .measurementUnpinned
        
        case 6: return .composeMismatch
        
        case 7: return .appIdMismatch
        
        case 8: return .bindingMismatch
        
        case 9: return .noLogAbsent
        
        case 10: return .regimeUnsupported
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VerdictReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case .ok:
            writeInt(&buf, Int32(1))
        
        
        case .quoteSigInvalid:
            writeInt(&buf, Int32(2))
        
        
        case .tcbOutOfDate:
            writeInt(&buf, Int32(3))
        
        
        case .collateralStale:
            writeInt(&buf, Int32(4))
        
        
        case .measurementUnpinned:
            writeInt(&buf, Int32(5))
        
        
        case .composeMismatch:
            writeInt(&buf, Int32(6))
        
        
        case .appIdMismatch:
            writeInt(&buf, Int32(7))
        
        
        case .bindingMismatch:
            writeInt(&buf, Int32(8))
        
        
        case .noLogAbsent:
            writeInt(&buf, Int32(9))
        
        
        case .regimeUnsupported:
            writeInt(&buf, Int32(10))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerdictReason_lift(_ buf: RustBuffer) throws -> VerdictReason {
    return try FfiConverterTypeVerdictReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerdictReason_lower(_ value: VerdictReason) -> RustBuffer {
    return FfiConverterTypeVerdictReason.lower(value)
}



extension VerdictReason: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Lowercase-hex SHA-256(eph_pub) — the channel binding placed in report_data[0:32].
 */
public func challengeHex(ephPub: Data) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_caladon_core_fn_func_challenge_hex(
        FfiConverterData.lower(ephPub),$0
    )
})
}
/**
 * SK = HKDF(X25519(my_private, their_public), info = label ‖ client_pub ‖ cvm_pub).
 */
public func deriveSessionKey(myPrivate: Data, theirPublic: Data, clientPub: Data, cvmPub: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSealError.lift) {
    uniffi_caladon_core_fn_func_derive_session_key(
        FfiConverterData.lower(myPrivate),
        FfiConverterData.lower(theirPublic),
        FfiConverterData.lower(clientPub),
        FfiConverterData.lower(cvmPub),$0
    )
})
}
/**
 * Open a sealed live-turn payload (`nonce ‖ ct`). Fails closed on tamper.
 */
public func openChat(sessionKey: Data, nonceCt: Data, accountId: String, v: Int64)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSealError.lift) {
    uniffi_caladon_core_fn_func_open_chat(
        FfiConverterData.lower(sessionKey),
        FfiConverterData.lower(nonceCt),
        FfiConverterString.lower(accountId),
        FfiConverterInt64.lower(v),$0
    )
})
}
/**
 * Open a sealed WMK (`nonce ‖ ct`). Fails closed on tamper.
 */
public func openWmk(sessionKey: Data, nonceCt: Data, accountId: String, v: Int64)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSealError.lift) {
    uniffi_caladon_core_fn_func_open_wmk(
        FfiConverterData.lower(sessionKey),
        FfiConverterData.lower(nonceCt),
        FfiConverterString.lower(accountId),
        FfiConverterInt64.lower(v),$0
    )
})
}
/**
 * Pad to a fixed bucket so the wire length reveals only the bucket, not the exact plaintext size.
 */
public func pad(plaintext: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePadError.lift) {
    uniffi_caladon_core_fn_func_pad(
        FfiConverterData.lower(plaintext),$0
    )
})
}
/**
 * Wrapping key = HKDF-SHA256(ikm = prf32, info = "caladon/passkey-wrapping/v1") → 32 bytes.
 * Deterministic in `prf32`. Fails closed on a non-32-byte PRF.
 */
public func passkeyDeriveWrappingKey(prf32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePasskeyError.lift) {
    uniffi_caladon_core_fn_func_passkey_derive_wrapping_key(
        FfiConverterData.lower(prf32),$0
    )
})
}
/**
 * Open (unwrap) the sealed seed (`wrapped` = `nonce ‖ ct`). Fails closed on a wrong passkey/PRF
 * or a tampered blob.
 */
public func passkeyUnwrapSeed(prf32: Data, wrapped: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePasskeyError.lift) {
    uniffi_caladon_core_fn_func_passkey_unwrap_seed(
        FfiConverterData.lower(prf32),
        FfiConverterData.lower(wrapped),$0
    )
})
}
/**
 * Seal (wrap) the 32-byte seed under the passkey-derived wrapping key. Random 24-byte nonce.
 * Returns `nonce ‖ ct`.
 */
public func passkeyWrapSeed(prf32: Data, seed: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePasskeyError.lift) {
    uniffi_caladon_core_fn_func_passkey_wrap_seed(
        FfiConverterData.lower(prf32),
        FfiConverterData.lower(seed),$0
    )
})
}
/**
 * Seal a live-turn payload to SK (purpose "chat"). Returns `nonce ‖ ct`.
 */
public func sealChat(sessionKey: Data, plaintext: Data, accountId: String, v: Int64)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSealError.lift) {
    uniffi_caladon_core_fn_func_seal_chat(
        FfiConverterData.lower(sessionKey),
        FfiConverterData.lower(plaintext),
        FfiConverterString.lower(accountId),
        FfiConverterInt64.lower(v),$0
    )
})
}
/**
 * Seal the WMK to SK for CVM delivery. Returns `nonce ‖ ct`.
 */
public func sealWmk(sessionKey: Data, wmk: Data, accountId: String, v: Int64)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSealError.lift) {
    uniffi_caladon_core_fn_func_seal_wmk(
        FfiConverterData.lower(sessionKey),
        FfiConverterData.lower(wmk),
        FfiConverterString.lower(accountId),
        FfiConverterInt64.lower(v),$0
    )
})
}
/**
 * Decode a recovery string back to the 32-byte seed. Fails closed on a bad
 * checksum/length/character.
 */
public func seedDecode(text: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSeedError.lift) {
    uniffi_caladon_core_fn_func_seed_decode(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Encode a 32-byte seed to the grouped Crockford-base32 + checksum recovery string.
 */
public func seedEncode(seed: Data)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSeedError.lift) {
    uniffi_caladon_core_fn_func_seed_encode(
        FfiConverterData.lower(seed),$0
    )
})
}
/**
 * Recover the exact plaintext from a padded buffer. Fails closed on a malformed buffer.
 */
public func unpad(padded: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePadError.lift) {
    uniffi_caladon_core_fn_func_unpad(
        FfiConverterData.lower(padded),$0
    )
})
}
/**
 * Fail-closed verification with collateral PASSED IN (offline/deterministic — the Swift
 * `DcapVerifier` fetches PCS collateral and hands it here). Never throws on a verification
 * FAILURE: returns a `Verdict` with `ok=false` and the specific reason.
 */
public func verifyQuote(quoteBytes: Data, collateralJson: String, infoJson: String, nowSecs: UInt64, expectedChallengeHex: String, pinned: PinnedSet) -> Verdict {
    return try!  FfiConverterTypeVerdict.lift(try! rustCall() {
    uniffi_caladon_core_fn_func_verify_quote(
        FfiConverterData.lower(quoteBytes),
        FfiConverterString.lower(collateralJson),
        FfiConverterString.lower(infoJson),
        FfiConverterUInt64.lower(nowSecs),
        FfiConverterString.lower(expectedChallengeHex),
        FfiConverterTypePinnedSet.lower(pinned),$0
    )
})
}
/**
 * X25519 public key for a 32-byte private scalar.
 */
public func x25519Public(privateBytes: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSealError.lift) {
    uniffi_caladon_core_fn_func_x25519_public(
        FfiConverterData.lower(privateBytes),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_caladon_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_caladon_core_checksum_func_challenge_hex() != 645) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_derive_session_key() != 40015) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_open_chat() != 63627) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_open_wmk() != 12181) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_pad() != 56056) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_passkey_derive_wrapping_key() != 44151) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_passkey_unwrap_seed() != 17782) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_passkey_wrap_seed() != 48547) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_seal_chat() != 32439) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_seal_wmk() != 62818) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_seed_decode() != 33732) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_seed_encode() != 31996) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_unpad() != 5473) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_verify_quote() != 62102) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_caladon_core_checksum_func_x25519_public() != 44449) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all